name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
        
            - name: List and Read File
              run: |
                echo "welcome to this super github action"
                ls -ltra
                cat README.md
            
            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Run for cover, I am a Dragon....." >> dragon.txt
            
            #- name: List Files
            #  run: ls
            
            #- name: Read File
            #  run: cat README.md