name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome
              run: echo "welcome to this super github action"
            
            - name: List Files
              run: ls
            
            - name: Read File
              run: cat README.md